services:
  - type: web
    name: express-hello-world
    runtime: node
    plan: free
    buildCommand: yarn install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
